### PR TITLE
TASK: Add validation pattern to Role name field

### LINKED ISSUE #5: Space in role name triggers error
The forms (create/edit) allow to enter a space (and probably other characters), that are disallowed.

- That leads to a validation error, but no explanation is given to the user
- The input field should use client-side validation

🤷‍♂️

### PR DESCRIPTION
**Pull request by lorenzulrich**
Additionally, a hint regarding allowed characters is added to the help text.

Fixes #5

### CODE REVIEW

**Comment by lorenzulrich** [comment]
I adjusted the pattern and description to match https://github.com/sandstorm/NeosAcl/blob/master/Classes/Domain/Model/DynamicRole.php#L20

**Comment by lorenzulrich** [comment]
@kdambekalns Maybe you're also interested in this.

**Review by kdambekalns — APPROVED** [review]
✅ by 👀

**Review by skurfuerst — APPROVED** [review]
thanks!

**Comment by skurfuerst** [comment]
sorry for the delay! don't hesitate to ping me on slack for such things :)

**Pull request merged**
